version: '3'

services:
  # Node.js
  node:
    build: .
    container_name: node
    tty: true
    ports:
      - 3000:3000
    # プロジェクトディレクトリにマウントする
    volumes:
      - ./app-next:/usr/src/app
    # ネットワーク
    networks:
      - default
    working_dir: /usr/src/app
    command: npm run dev && npx prisma migrate dev --name init


  # データベース
  db:
    image: mysql:latest
    container_name: docker-nextjs-mysql-sample-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      # 設定ファイルディレクトリにマウントする
      - ./mysql/conf.d:/etc/mysql/conf.d
      # DB初期化ディレクトリにマウントする
      - ./mysql/init.d:/docker-entrypoint-initdb.d
      - docker-nextjs-mysql-sample-mysql-data:/var/lib/mysql
    # ネットワーク
    networks:
      - default

volumes:
  docker-nextjs-mysql-sample-mysql-data:

# ネットワーク
networks:
  default:
    driver: bridge
    